export const translations = {
    french: {
      title: "Détails du Stock",
      productName: "Nom du produit",
      availableQuantity: "Quantité disponible",
      stockDate: "Date d'entrée en stock",
      price: "Prix",
      stockType: "Type du stock",
      lastMovement: "Dernier mouvement",
      inStock: "En stock",
      added: "Ajout",
      removed: "Retrait",
    },
    arabic: {
      title: "تفاصيل المخزون",
      productName: "اسم المنتج",
      availableQuantity: "الكمية المتوفرة",
      stockDate: "تاريخ الدخول إلى المخزون",
      price: "السعر",
      stockType: "نوع المخزون",
      lastMovement: "آخر حركة",
      inStock: "في المخزون",
      added: "إضافة",
      removed: "سحب",
    },
  };